const CheckListActionTypes = {
  ADD_TO_CHECKLIST: 'ADD_TO_CHECKLIST',
  REMOVE_FROM_CHECKLIST: 'REMOVE_FROM_CHECKLIST',
  INCREMENT_ITEM: 'INCREMENT_ITEM',
  DECREMENT_ITEM: 'DECREMENT_ITEM',
  CLEAR_LIST: 'CLEAR_LIST',
};

export default CheckListActionTypes;
